package:
  name: jetset
  version:  {{ os.environ.get('PKG_VERSION') }}

source:
  path: ../../../

build:
  preserve_egg_dir: True
  script_env:
    - JETSETBESSELBUILD

requirements:

  build:
    - swig>3.0.0
    - python

  run:
  - scipy
  - numpy
  - astropy>=4.0
  - matplotlib>3.1.0
  - future
  - iminuit>=1.3.7,<2
  - corner
  - six
  - emcee>=3.0.0
  - pyyaml
  - pyqt
  - pytest
  - numba






about:
  home: https://github.com/andreatramacere/jetset
  license: BSD-3
  summary: ''
  license_family: BSD

extra:
  recipe-maintainers:
    - andreatramacere