{% set data = load_setup_py_data(setup_file='../../../setup.py', from_recipe_dir=True) %}
{% set version = data.get('version')  %}

package:
  name: jetset
  version:  {{ version }}

source:
  path: ../../../

build:
  preserve_egg_dir: True
  script_env:
    - JETSETBESSELBUILD

requirements:

  build:
    - swig>3.0.0
    - python 
    - setuptools


  run:
  - scipy>=1.5.0
  - numpy>=1.16
  - astropy>=4.0
  - matplotlib>3.1.0
  - future
  - iminuit
  - corner
  - six
  - emcee>=3.0.0
  - pyyaml
  - pyqt
  - pytest
  - numba
  - jupyter
  - ipython
  - tqdm
  - dill
 # - sherpa



about:
  home: https://github.com/andreatramacere/jetset
  license: BSD-3
  summary: ''
  license_family: BSD

extra:
  recipe-maintainers:
    - andreatramacere