name: pip build-test

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
        python-version: [3.8]

    steps:

      - name: Clone Repository (Latest)
        uses: actions/checkout@v2

      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: set env JETSETBESSELBUILD
        run: |
          echo "FALSE">JETSETBESSELBUILD
          echo "JETSETBESSELBUILD=$(cat JETSETBESSELBUILD)" >> $GITHUB_ENV

      - name: echo env TEST
        run: |
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"


      - name: Install swig
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                  sudo apt-get update; sudo apt-get install swig
             elif [ "$RUNNER_OS" == "macOS" ]; then
                  brew install swig
             else
                  echo "$RUNNER_OS not supported"
                  exit 1
             fi

      - name: Setup pip
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: adapt req
        run: |
          python .github/workflows/adapt_reqirements_to_git_action.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: pip build
        run: |
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"
          python setup.py clean
          python setup.py sdist bdist_wheel
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"

      - name: pip install
        run: |
          pip install dist/*.whl

      - name: make test env
        run: |
          cp -r jetset/tests/test*.py  .github/action_test/


      - name: test
        working-directory: .github/action_test/
        run: |
          pytest -sv --pyargs test_functions::test_jet

      - name: set pkg version
        run: |
          echo "PKG_VERSION=$(cd ../../ && python -c "import jetset;print(jetset.__version__)")" >> $GITHUB_ENV

      - name: echo pkg version
        run: |
          echo "PKG_VERSION=${{env.PKG_VERSION}}"

      - name: upload .whl
        uses: actions/upload-artifact@v2
        with:
          name: jetset-${{ env.PKG_VERSION }}-${{ matrix.os }}-pip-binary
          path: dist/*.whl

      - name: upload sdist
        uses: actions/upload-artifact@v2
        with:
          name: jetset-${{ env.PKG_VERSION }}-${{ matrix.os }}-src
          path: dist/*.tar.gz

