name: conda build-test

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
        python-version: [3.8]

    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2

      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: set env JETSETBESSELBUILD
        run: |
          echo "FALSE">JETSETBESSELBUILD
          echo "JETSETBESSELBUILD=$(cat JETSETBESSELBUILD)" >> $GITHUB_ENV


      - name: echo env TEST
        run: |
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"


      - name: setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge,astropy

      - name: Install dependencies
        run: |
          conda config --set always_yes yes
          conda install conda-build
          conda install -c conda-forge emcee">=3.0.0"
          conda install -c astropy --file requirements.txt
          conda install  pytest

      - name: build
        run: |
          python setup.py clean
          python setup.py install > install.log 2>install.err

      #- name: test
      #  run: |
      #    pytest --pyargs jetset.tests.test_functions::test_short

      - name: set pkg version
        run: |
          echo "PKG_VERSION=$(cd ../../ && python -c "import jetset;print(jetset.__version__)")" >> $GITHUB_ENV

      - name: echo pkg version
        run: |
           echo "PKG_VERSION=${{env.PKG_VERSION}}"


      - name: conda build
        working-directory: .github/conda-pipeline/github/
        run: |
          conda config --set anaconda_upload no
          conda build purge
          conda build .  -c defaults -c astropy -c conda-forge
          conda build . --output > ./CONDABUILDJETSET.txt

      - name: set env CONDABUILDJETSET
        working-directory: .github/conda-pipeline/github/
        run:  echo "CONDABUILDJETSET=$(cat CONDABUILDJETSET.txt)"  >> $GITHUB_ENV

      - name: set pkg version
        run: |
          echo "PKG_VERSION=$(cd ../../ && python -c "import jetset;print(jetset.__version__)")" >> $GITHUB_ENV

      - name: echo pkg version
        run: |
          echo "PKG_VERSION=${{env.PKG_VERSION}}"

      - name: upload conda pkg
        uses: actions/upload-artifact@v2
        with:
          name: jetset-${{ env.PKG_VERSION }}-${{ matrix.os }}-conda-binary
          path: ${{ env.CONDABUILDJETSET }}

