name: pip build-test

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
        python-version: [3.8]

    steps:

      - name: Clone Repository (Latest)
        uses: actions/checkout@v2

      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: set env JETSETBESSELBUILD
        run: |
          echo "FALSE">JETSETBESSELBUILD
          echo "JETSETBESSELBUILD=$(cat JETSETBESSELBUILD)" >> $GITHUB_ENV

      - name: echo env TEST
        run: |
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"

     # - name: Print env TEST
     #   run: |
     #     echo "TEST=${TEST}"
     #     printenv

     # - uses: actions/upload-artifact@v2
     #   with:
     #     name: ${{ matrix.os }}-TEST
     #     path: ${{ env.TEST }}
      - name: Install swig
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                  sudo apt-get update; sudo apt-get install swig
             elif [ "$RUNNER_OS" == "macOS" ]; then
                  brew install swig
             else
                  echo "$RUNNER_OS not supported"
                  exit 1
             fi

      - name: Setup pip
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup pip
        run: |
          python3 adapt_reqirements_to_git_action.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements_action.txt ]; then pip install -r requirements_action.txt; fi

      - name: pip build
        run: |
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"
          python setup.py clean
          python setup.py sdist bdist_wheel
          python setup.py install
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"

      #- name: test
      #  run: |
      #    pytest --pyargs jetset.tests.test_functions::test_short

      - name: set pkg version
        run: |
          echo "PKG_VERSION=$(cd ../../ && python -c "import jetset;print(jetset.__version__)")" >> $GITHUB_ENV

      - name: echo pkg version
        run: |
          echo "PKG_VERSION=${{env.PKG_VERSION}}"

      - name: upload .whl
        uses: actions/upload-artifact@v2
        with:
          name: $jetset-{{ matrix.os }}-${{ env.PKG_VERSION }}-pip-binary
          path: dist/*.whl
      - name: upload sdist
        uses: actions/upload-artifact@v2
        with:
          name: $jetset-{{ matrix.os }}-${{ env.PKG_VERSION }}-pip-src
          path: dist/*.tar.gz

