name: pip build-test

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
jobs:
  clone:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
        python-version: [3.8]

    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2

      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}


  swig-linux:
    runs-on: ubuntu-latest
    needs: clone
    steps:
     - run: |
          sudo apt-get update
          sudo apt-get install swig

  swig-mac:
    runs-on: macos-10.15
    needs: clone
    steps:
      - run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install swig

  buildpip:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup pip
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set env JETSETBESSELBUILD
        run: |
          echo 'FALSE' >> JETSETBESSELBUILD

      - name: Print env JETSETBESSELBUILD
        run: |
          echo "JETSETBESSELBUILD=${JETSETBESSELBUILD}"
          printenv

      - name: pip build
        run: |
          python3 setup.py clean
          python3 setup.py sdist bdist_wheel

      #- name: test
      #  run: |
      #    pytest --pyargs jetset.tests.test_functions::test_short

      - name: Set env PKG_VERSION
        run: echo "$(cd ../../ && python3 -c "import jetset;print(jetset.__version__)")">>PKG_VERSION

      - name: Print env PKG_VERSION
        run: |
          echo "PKG_VERSION=${PKG_VERSION}"
          printenv

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ env.PKG_VERSION }}-package
          path: dist/*
          #path: ${{ env.CONDABUILDJETSET }}

