name: Test CI/CD jetset

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.13]
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge,astropy
      - run: conda --version
      - run: which python
      - name: Install dependencies
      run:
        conda install --yes   -c conda-forge emcee">=3.0.0"
        conda install --yes   -c astropy --file requirements.txt
        conda install --yes pytest
    #- name: Lint with flake8
    #  run: |
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: build
        - run:
            python setup.py clean
            python setup.py install > install.log 2>install.err
