name: Test CI/CD jetset

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
        python-version: [3.7]
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge,astropy

      - name: Install dependencies
        run: |
          conda config --set always_yes yes
          conda install conda-build
          conda install -c conda-forge emcee">=3.0.0"
          conda install -c astropy --file requirements.txt
          conda install  pytest
  
      - name: build
        run: |
          python setup.py clean
          python setup.py install > install.log 2>install.err

      #- name: test
      #  run: |
      #    pytest --pyargs jetset.tests.test_functions::test_short


      - name: conda build
        working-directory: ./CICD/conda-pipeline/linux/
        run: |
#          echo 'pwd' $PWD
          conda config --set anaconda_upload no
          conda build purge
          conda build .  -c defaults -c astropy -c conda-forge > build.log 2>build.err
#         export CONDABUILDJETSET=$(conda-build . --output)
#         #echo  'CONDABUILDJETSET' $CONDABUILDJETSET
#         #echo '---> done'

      #- name: echo build
      #  shell: bash
      #  run: |
      #    export CONDABUILDJETSET=$(conda-build . --output)
      #    echo  $CONDABUILDJETSET

      - name: set environment variables
        uses: allenevans/set-env@v1.0.0
          with:
            CONDABUILDJETSET: conda-build . --output


      - name: Printenv
          run: |
            echo "CONDABUILDJETSET=${CONDABUILDJETSET}"
            printenv

      - uses: actions/upload-artifact@v2
        with:
            name: artifact
            path: $CONDABUILDJETSET

