name: pip build-test

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      tags:
        description: tag
        required: false
      skip_test:
        description: skip test
        required: false

jobs:
  create_release:
    if: github.event.inputs.tags != null
    runs-on: ubuntu-latest
    steps:
    - name: 'Clone Repository (Latest)'
      uses: actions/checkout@v2

    - name: 'Clone Repository (Custom Ref)'
      uses: actions/checkout@v2
      if: github.event.inputs.git-ref != ''
      with:
        ref: ${{ github.event.inputs.git-ref }}


    - name: 'Create release'
      if: github.event.inputs.tags != null
      uses: softprops/action-gh-release@v1
      id : create_release
      #if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release  ${{ github.event.inputs.tags }}
        tag_name: ${{ github.event.inputs.tags }}

    #- name: 'Output Release URL File'
    #  run: |
    #    echo "${{ steps.create_release.outputs.url }}" > release_url.txt
    #    echo "release url=${{ steps.create_release.outputs.url }}"

    #- name: 'Save Release URL File for publish'
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: release_url
    #    path: release_url.txt


  build_pip:
    needs: [create_release]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
        python-version: [3.7,3.8,3.9]

    steps:
      - name: 'Clone Repository (Latest)'
        uses: actions/checkout@v2

      - name: 'Clone Repository (Custom Ref)'
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: 'set env JETSETBESSELBUILD'
        run: |
          echo "FALSE">JETSETBESSELBUILD
          echo "JETSETBESSELBUILD=$(cat JETSETBESSELBUILD)" >> $GITHUB_ENV

      - name: 'echo env TEST'
        run: |
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"


      - name: 'Install swig'
        run: |
           if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get update; sudo apt-get install swig
           elif [ "$RUNNER_OS" == "macOS" ]; then
                brew install swig
           else
                echo "$RUNNER_OS not supported"
                exit 1
           fi

      - name: 'Setup pip'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: 'adapt req'
        run: |
          python .github/workflows/adapt_reqirements_to_git_action.py

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 'pip build'
        run: |
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"
          python setup.py clean
          python setup.py sdist bdist_wheel
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"

      - name: 'pip install'
        run: |
          pip install dist/*.whl

      - name: 'make test env'
        run: |
          cp -r jetset/tests/test*.py  .github/action_test/

      - name: 'test'
        if: github.event.inputs.skip_test != 'yes'
        working-directory: .github/action_test/
        run: |
          echo $(running tests!)
          pytest --pyargs jetset.tests.test_functions::TestFull

