name: conda test

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      skip_test:
        description: skip test
        required: false

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
    - name: 'Clone Repository (Latest)'
      uses: actions/checkout@v2

    - name: 'Clone Repository (Custom Ref)'
      uses: actions/checkout@v2
      if: github.event.inputs.git-ref != ''
      with:
        ref: ${{ github.event.inputs.git-ref }}


  build_conda:
    needs: [clone]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-10.15 ]
        python-version: [ 3.8,3.9,'3.10']

    steps:
      - name: 'Clone Repository (Latest)'
        uses: actions/checkout@v2

      - name: 'Clone Repository (Custom Ref)'
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      
      - uses: mamba-org/setup-micromamba@v1
        with:
          # the create command looks like this:
          # `micromamba create -n test-env python=3.10 numpy`
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }}
            swig>=3.0.0 
            conda-build
            pytest
          
          generate-run-shell: true
          init-shell: bash

      - name: 'Install dependencies'
        shell: bash
        run: |
          cat ~/.bash_profile
          export MAMBA_ROOT_PREFIX=~/micromamba
          export MAMBA_EXE=~/micromamba-bin/micromamba
          export CONDARC=~/micromamba-bin/.condarc
          micromamba activate test-env
          micromamba config --set always_yes yes
          micromamba install -c astropy -c conda-forge --file requirements.txt
         
          
  

      - name: 'set env JETSETBESSELBUILD'
        run: |
          echo "FALSE">JETSETBESSELBUILD
          echo "JETSETBESSELBUILD=$(cat JETSETBESSELBUILD)" >> $GITHUB_ENV

      - name: 'echo env TEST'
        run: |
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"

      - name: 'build '
        run: |
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"
          python setup.py clean
          python setup.py install
          python setup.py clean
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"

      - name: 'set pkg version'
        run: |
         echo "PKG_VERSION=$(cd ../../ && python -c "import jetset;print(jetset.__version__)")" >> $GITHUB_ENV

      - name: 'echo pkg version'
        run: |
          echo "PKG_VERSION=${{env.PKG_VERSION}}"

      - name: 'conda build'
        working-directory: .github/conda-pipeline/github/
        run: |
          micromamba config --set anaconda_upload no
          micromamba build purge
          micromamba build .  -c conda-forge -c astropy
          micromamba build . --output > ./CONDABUILDJETSET.txt  
      
      - name: 'set env CONDABUILDJETSET'
        working-directory: .github/conda-pipeline/github/
        run: |
          echo $(cat CONDABUILDJETSET.txt)
          echo "CONDABUILDJETSET=$(tail -1 CONDABUILDJETSET.txt)"  >> $GITHUB_ENV

      - name: 'echo env CONDABUILDJETSET'
        working-directory: .github/conda-pipeline/github/
        run: echo "CONDABUILDJETSET=${{env.CONDABUILDJETSET}}"

      - name: 'conda install'
        run: |
          conda install --yes --offline $CONDABUILDJETSET

      #- name: 'make test env'
      #  run: |
      #    cp -r jetset/tests/test*.py  .github/action_test/

      - name: 'test'
        if: github.event.inputs.skip_test != 'yes'
        working-directory: .github/action_test/
        run: |
          echo $(running tests!)
          pytest --disable-warnings  --pyargs  -vvv jetset.tests.test_jet_model
          pytest  --pyargs -vvv jetset.tests.test_hadronic_energetic
          pytest  --pyargs -vvv jetset.tests.test_integration::TestIntegration
