name: Test CI/CD jetset

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-10.15]
        python-version: [3.7]
    steps:

      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge,astropy

      - name: Install dependencies
        run:|
          conda install --yes   -c conda-forge emcee">=3.0.0"
          conda install --yes   -c astropy --file requirements.txt
          conda install --yes pytest
  
      - name: build
        run:|
          python setup.py clean
          python setup.py install > install.log 2>install.err
