name: pip test

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
      skip_test:
        description: skip test
        required: false

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
    - name: 'Clone Repository (Latest)'
      uses: actions/checkout@v2

    - name: 'Clone Repository (Custom Ref)'
      uses: actions/checkout@v2
      if: github.event.inputs.git-ref != ''
      with:
        ref: ${{ github.event.inputs.git-ref }}


  build_pip:
    needs: [clone]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest]
        os: [macOS-12,ubuntu-latest]
        cibw_python: ["cp38-*", "cp39*", "cp310-*"]
        cibw_manylinux: [manylinux2014]
        cibw_arch: ["x86_64"]


    steps:
      - name: 'Clone Repository (Latest)'
        uses: actions/checkout@v2

      - name: 'Clone Repository (Custom Ref)'
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: 'set env JETSETBESSELBUILD'
        run: |
          echo "FALSE">JETSETBESSELBUILD
          echo "JETSETBESSELBUILD=$(cat JETSETBESSELBUILD)" >> $GITHUB_ENV

      - name: 'echo env TEST'
        run: |
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"
          python -v


      - name: 'Install swig'
        run: |
           if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get update; sudo apt-get install swig
           elif [ "$RUNNER_OS" == "macOS" ]; then
                brew install swig
           else
                echo "$RUNNER_OS not supported"
                exit 1
           fi

      - name: 'Setup pip'
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: 'adapt req'
        run: |
          python .github/workflows/adapt_reqirements_to_git_action.py

      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: 'pip build'
        run: |
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"
          python setup.py clean
          echo "JETSETBESSELBUILD=${{ env.JETSETBESSELBUILD }}"
      
      - name: 'pip build install sdist'
        run: |
          python setup.py sdist 
          pip install dist/*.tar.gz
          
      - name: 'test sdist'
        working-directory: .github/action_test/
        run: |
          echo $(running tests!)
          pytest --disable-warnings  --pyargs  -vvv jetset.tests.test_jet_model
      
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

      
      #- name: 'pip build install wheel'
      #  run: |
      #    pip uninstall --yes jetset
      #    python setup.py clean 
      #    python setup.py  bdist_wheel 
      #    pip install dist/*.whl
      

      - uses: actions/checkout@v3

      - uses: pypa/cibuildwheel@v2.11.4
        env:
          CIBW_SKIP: "*-musllinux_*"
          CIBW_BUILD: ${{ matrix.cibw_python }}
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.cibw_manylinux }}
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_ARCHS_MACOS: "x86_64"
          #CIBW_TEST_COMMAND: pytest  --disable-warnings  --pyargs  -vvv jetset.tests.test_jet_model && pytest  --pyargs -vvv jetset.tests.test_hadronic_energetic && pytest  --pyargs -vvv jetset.tests.test_integration::TestIntegration
  
      - name: Show files
        run: ls -lh wheelhouse
        shell: bash
  
      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash
      
      

      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
      
   